id: P779AB763
initial_creation_type: input
source_metadata:
  title: Katok Rigdzin Tsewang Norbu
  language: en
  description: 'Texts by Katok Rigdzin Tsewang Norbu (kaḥ thog rig ''dzin tshe dbang
    nor bu, 1698–1755):'
  volume:
    4f91b464a0b84f2181916e395f155d9a:
      title: Advice for a King
      parent: Advice
created_at: '2022-03-01T00:15:32.941568'
last_modified_at: '2022-03-01T00:15:32.941574'
